# Generated by Django 3.2 on 2021-04-24 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('task_content', models.CharField(max_length=255)),
                ('task_data', models.CharField(max_length=10)),
                ('task_hour', models.IntegerField()),
                ('task_completed', models.BooleanField(default=False)),
                ('task_remember', models.BooleanField(default=False)),
            ],
        ),
    ]
