# Generated by Django 3.2 on 2021-04-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_hour',
            field=models.CharField(max_length=5),
        ),
    ]
